import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { signIn } from "next-auth/react";

import { ImageUpload } from "../components/forms/ImageUpload";
import Nav from "../components/nav/Nav";
import { api } from "../utils/api";
import { isProfileComplete } from "./(utils)/funcs";
import { useRouter } from "next/router";



const Home: NextPage = () => {

  const [imgUrl, setImgUrl] = useState<string>("");
  //     ^?
  const router = useRouter();

  const meQuery = api.account.me.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="flex min-h-screen flex-col items-center justify-center">
        <ImageUpload
          setUrl={setImgUrl}
          label="Upload an image"
        />
        {
          imgUrl && <img src={imgUrl} />
        }
      </main>
    </>
  );
};

export default Home;

